[profile.default]
auto_detect_solc = true
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
cache_path  = 'forge-cache'
gas_reports = ['*']
fs_permissions = [{ access = 'read', path = './test/prove_api/payload'}, { access = 'read', path = './out'}]
via_ir = true
optimizer = true
optimizer_runs = 200
# Suppress warnings from specific files
ignored_warnings_from = ["./contracts/core/native_fallback/L1/Registry.sol"]

[fmt]
wrap_comments = true
number_underscore = "thousands"
ignore = ["lib/*"]

# See more config options https://book.getfoundry.sh/reference/config.html
