name: Release

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # Note: run this before we generate artifacts, otherwise the release will include redundant contracts. 
      - name: Contract Unit Tests
        run: forge test

      - name: Check contract sizes
        run: rm -rf out release-artifacts && forge build --force contracts/core --sizes --deny-warnings

      - name: Save compiled contracts and ABIs
        if: success()
        run: |
          mkdir -p release-artifacts
          cp -r out release-artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-contracts
          path: release-artifacts

  release:
    runs-on: ubuntu-latest
    needs: artifacts
    environment: release
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: compiled-contracts
          path: ./release-artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release-artifacts/**
          generate_release_notes: true
          draft: false
          prerelease: false
          token: ${{ secrets.RELEASE_TOKEN }}

  registries:
    runs-on: ubuntu-latest
    environment: release
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Get Latest Version
        id: version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.3'

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - uses: actions/setup-node@v4
        with:
          node-version: '22.3.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      # Ensure /v4 is updated as the major version changes
      - name: Update Go Registry
        run: |
          GOPROXY=proxy.golang.org go list \
          -m github.com/polymerdao/prover-contracts@${{ steps.version.outputs.release }}

      - name: Update NPM Registry
        run: |
          bun install
          bun run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
